Real time status
Jean-Serge/ops_inventory pull request #5
Opened 2017-07-08 18:51 UTC by Jean-Serge

2017-07-18 03:56 UTC, xvw requested changes
La seule modification "réellement importante" à mon sens est le map/find ;)

2017-07-18 03:56 UTC, xvw commented on web/controllers/digital_ocean_controller.ex
>                  ).status
Cette partie du code est fragile, find pouvant ne "rien renvoyer". Je pense qu'il faudrait plutôt opter pour un filterMap/fold (ou une autre construction de code) ;)

2017-07-18 03:56 UTC, xvw commented on web/models/server.ex
> +      from s in Server,
Par soucis de performance (même si ce n'est pas vraiment ce que j'ai fait dans Divine) on préférera utiliser la primitive assoc pour faire des jointures. Mais c'est du détail.

2017-07-18 12:10 UTC, xvw commented on web/controllers/digital_ocean_controller.ex
> +                nil ->
Largement mieux ! 
(Sinon, pour le "skill", ce serait peut être le moment idéal pour utiliser la syntaxe "with")

https://blog.drewolson.org/elixirs-secret-weapon/ 

Mais sinon je valide la Review ! 
Good Work !

2017-07-18 12:10 UTC, xvw approved these changes

2017-07-27 21:19 UTC, xvw commented on web/models/server.ex
> +      join: d in assoc(s, :droplet),
👍

2017-07-29 19:57 UTC, Jean-Serge commented on web/controllers/digital_ocean_controller.ex
> +                nil ->
Je ne comprend pas vraiment à quoi ça m'avancerait dans le cas présent d'utiliser `with`

2017-07-30 13:29 UTC, merged